### ISSUE TITLE
Eps shown as low quality despite being higher quality

### ISSUE THREAD

**Issue by udochrist** [SickRage/sickrage-issues#131]
For a show I have set the quality to hd720p I have overwritten the files with 1080p versions and manually marked them as "Downloaded 1080p hdtv". These eps are now flagged as lower quality / yellow instead of simply downloaded/ green.

SR Version:	BRANCH: (master) / COMMIT: (54ed43c5053d3bb8d267bf62b9a68505533a4a4d)

**Comment by OmgImAlexis** [comment]
@miigotu

**Comment by miigotu** [comment]
It is supposed to be that way. It is not a wanted quality, so it is marked as an "unwanted quality"

**Comment by fernandog** [comment]
Set as "Archived 1080p HDTV"

**Comment by udochrist** [comment]
Maybe the name should be unwanted then and not "low" as this seems a bit misleading. 
Besides this seems to be a "newer feature" since I've done the exact same thing earlier without triggering this behavior.

**Comment by udochrist** [comment]
I thought "archived" was meant to denote that you have that ep but it's not controlled/loaded into SR (i.e. On DVDs/bluray)

**Comment by miigotu** [comment]
@udochrist many things are in a rolling update atm. We cant change everything at once or no-one will have any clue what is going on.

**Comment by Amadeus-** [comment]
I mentioned the other day regarding the fact that we need to change the web interface labels from "low quality" to "unwanted quantity".   But yea, that's what is happening.     

As fern mentioned, the easy solution is to mark it as "archived" and then it will disappear.   "Archived", from what I understand, basically means that you've moved the file away from SR and that SR shouldn't care about it anymore (unless you change its status at some point in the future.)

Honestly, I have SR config (on my installation) set to 'auto set as "archived"' after download.   For me, since I prefer SDTV (but will accept 720p), it avoids the issue that you're encountering.
