### ISSUE TITLE
NameError: 'show_names' is not defined

### ISSUE THREAD

**Issue by hydex86** [SickRage/sickrage-issues#291]
I'm running Sickrage on Synology and when I try to go to section "Manage missed subtitles" i got this error. It was working fine until last update:

```
    NameError: 'show_names' is not defined

    <%block name="scripts"> <script type="text/javascript" src="${srRoot}/js/manageSubtitleMissed.js?${sbPID}"></script> </%block> <%block name="content"> <div id="content960"> % if not header is UNDEFINED: <h1 class="header">${header}</h1> % else: <h1 class="title">${title}</h1>
/usr/local/sickrage/var/SickRage/gui/slick/views/manage_subtitleMissed.mako, line 11:
    <%block name="content">
    /usr/local/sickrage/var/SickRage/gui/slick/views/layouts/main.mako, line 270:
    /usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 890:
     callable_(context, *args, **kwargs)
     /usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 864:
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
    /usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 829:
    **_kwargs_for_callable(callable_, data))
    /usr/local/sickrage/var/SickRage/lib/mako/template.py, line 454:
    as_unicode=True)
    /volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py, line 191:
    return self.mako_lookup.get_template(template_name).render_unicode(**template_kwargs)
    /volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py, line 194:
    return self.render_string(template_name, **kwargs)
    /volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py, line 2989:
    topmenu='manage')
    /volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py, line 219:
    return function(**kwargs)
```

Any ideas?

**Comment by duramato** [comment]
Try clearing your cache/mako

**Comment by neoatomic** [comment]
Just tested and working fine here on my DS415+. 
Its probbebly the Cache that has gone bad. (Or you are still on the old Repository)

**Comment by nickveldrin** [comment]
Can this be reopened?

I have the latest master build as of today (12/30) and get the same error when i try to go to subtitle management, since it's not downloading subtitles. Stopping sickrage and deleting the cache.db doesn't fix it.

http://thenas:8083/manage/subtitleMissed/
<code>
Error !

NameError: 'show_names' is not defined

<%block name="scripts"> <script type="text/javascript" src="${srRoot}/js/manageSubtitleMissed.js?${sbPID}"></script> </%block> <%block name="content"> <div id="content960"> % if not header is UNDEFINED: <h1 class="header">${header}</h1> % else: <h1 class="title">${title}</h1>
/usr/local/sickbeard-custom/var/SickBeard/gui/slick/views/manage_subtitleMissed.mako, line 11:
<%block name="content">
/usr/local/sickbeard-custom/var/SickBeard/gui/slick/views/layouts/main.mako, line 270:
/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py, line 890:
callable_(context, *args, **kwargs)
/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py, line 864:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py, line 829:
**_kwargs_for_callable(callable_, data))
/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py, line 454:
as_unicode=True)
/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py, line 191:
return self.mako_lookup.get_template(template_name).render_unicode(**template_kwargs)
/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py, line 194:
return self.render_string(template_name, **kwargs)
/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py, line 2989:
topmenu='manage')
/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py, line 219:
return function(**kwargs)
</code>

**Comment by duramato** [comment]
Delete your Cache/mako ,not cache.db

**Comment by nickveldrin** [comment]
I deleted the whole code repository and repulled it down. Works now. Thank you!

**Comment by labrys** [comment]
What commit are you on @nickveldrin

**Comment by zaggash** [comment]
Hello,

Same issue here.
Lastest commit at the time : 9226ba5efba06fb9defc5272f03dae5d6d1c4145

Tried to remove the cache folder.
The cache.db.

I also tried to re-clone the whoile depot and stilll the same error :

NameError: 'show_names' is not defined

8
<%block name="scripts">
9
<script type="text/javascript" src="${srRoot}/js/manageSubtitleMissed.js?${sbPID}"></script>
10
</%block>
11
<%block name="content">
12
<div id="content960">
13
% if not header is UNDEFINED:
14
    <h1 class="header">${header}</h1>
15
% else:
16
    <h1 class="title">${title}</h1>

**Comment by labrys** [comment]
@zaggash @nickveldrin You are both on the old repository.  This should go away after you switch to https://github.com/SickRage/Sickrage

**Comment by zaggash** [comment]
Or actually maybe not !
If I can read this, I just wrote my issue request in the wrong channel


https://github.com/sickragetv/sickrage

!!! IMPORTANT MEMBER ALERT !!!

Currently there have been several reports of attempts to trick our members into switching to a new sickrage repo being told that the current one is no longer operational, DO NOT BE FOOLED this is a poor attempt by several EX-team members to decieve you into switching to their UNOFFICIAL CLONED SickRage application/site/repo. Please note that if SiCKRAGE ever needed to move to a new site or change its address there is already code in place to do this automatically and securely by me, if you do manually change this information SiCKRAGE accepts no liability or consequences of anything afterwards. If you receive any such attempts/requests please please email sickrage.tv@gmail.com promptly so that we can deal with it accordingly!

SickRage

**Comment by duramato** [comment]
@zaggash you need to get yourself informed...
https://github.com/SickRage/sickrage-issues/issues/3
Read that up and then make assumptions

**Comment by zaggash** [comment]
Plz dont be so rude.
I just try to figure this out.

There is not so many informations about it.

And yes I get myself informed here :
https://sickrage.tv/forums/forum/main-category/latest-news/30585-massive-changes-being-made

**Comment by duramato** [comment]
@zaggash Im not beeing rude but if you want to know everything, its all explained here http://pastebin.com/raw/XgMreCb2

**Comment by labrys** [comment]
@zaggash Of course it's your decision which repository to stay with, however we can not provide support for the old repository as we have made so many changes, bug fixes, and improvements since then.

**Comment by zaggash** [comment]
@labrys I totally understand.
Sorry for my mistake.
Obviously I posted the issue in the wrong tracker :)

I'll try to find myself the fork I will follow.

**Comment by labrys** [comment]
@zaggash FYI: The old issue tracker is closed and will likely remain so

**Comment by nickveldrin** [comment]
I figured out the repo change a half day or day after I posted about my issue, and all is well in the new code. Appreciate everyone's help!

**Comment by neoatomic** [comment]
Yeah, its a big mess on the old repo. Lots of stuff is broken and no proper support.

And all the misinformation he is putting out there is confusing users. So if you bump into others with the same problem (aka using the old repo) just let them now we all moved here. :)
