### ISSUE TITLE
Windows 10 pythonw problem

### ISSUE THREAD

**Issue by fastdriver** [SickRage/sickrage-issues#43]
System info: windows 10 and python version 2.7.10

Problem: SickBeard.py works fine with python.exe but does not work with pythonw.exe its like nothing happens, does not generate any files (like config etc.) and pythonw.exe is not on the running  processes list.I tried unistall/install  both 32bit and 64bit versions of python.
Btw the old repo works fine.

**Comment by miigotu** [comment]
"Btw the old repo works fine." please don't compare us to the other repo. If it is broken here it is also broken there on develop.

We are working on improving build testing and windows testing, so hopefully can fix this soon.

**Comment by fastdriver** [comment]
lol i am not comparing you to the other repo.I am just trying to give some info to narrow down the problem...Sorry if I have offended you, that was not my intention.

**Comment by labrys** [comment]
@fastdriver I'm one of the windows testers, I'll test this on Win 10 x64 in a minute

**Comment by labrys** [comment]
Confirmed and looking into it

**Comment by labrys** [comment]
It's being caused while trying to set encoding... specifically `getattr(sys.stdout, 'device', sys.stdout)` in
`SickRage().start()`:

```python
if not sickbeard.SYS_ENCODING or sickbeard.SYS_ENCODING.lower() in ('ansi_x3.4-1968', 'us-ascii', 'ascii', 'charmap') or \
    (sys.platform.startswith('win') and sys.getwindowsversion()[0] >= 6 and getattr(sys.stdout, 'device', sys.stdout).encoding.lower() in ('cp65001', 'charmap')):
    sickbeard.SYS_ENCODING = 'UTF-8'
```
Looking into a fix now.

**Comment by labrys** [comment]
K got a fix... testing and I'll do a PR

**Comment by fastdriver** [comment]
After some googling i found out that Standard streams sys.stdin, sys.stdout and sys.stderr are not  available for pythonw.exe

**Comment by labrys** [comment]
yeah we knew that but didn't think that test would cause issues., apparently it does :)

**Comment by miigotu** [comment]
It isnt that they arent available afaik, its that they redirect to nothingness

**Comment by labrys** [comment]
actually in python 2 they arent available, in 3 they result in None

**Comment by labrys** [comment]
from http://stackoverflow.com/questions/24835155/pyw-and-pythonw-does-not-run-under-windows-7/30310192#30310192:

Differences between Python 2.x and Python 3.x:

When a script is run with pythonw.exe,  sys.stdin, sys.stdout, and sys.stderr:

in Python 2.x: have invalid file descriptors
The eventual result when trying to write to sys.stdout or sys.stderr is the following exception: IOError: [Errno 9] Bad file descriptor
Pitfall: Due to output buffering, this exception may not surface until you've output, say, 4K bytes; you can provoke it instantly by invoking pythonw.exe with -u (for unbuffered output).
print() blindly tries to sys.stdout (by default), so it provokes this exception sooner or later.
in Python 3.x: are set to None
This is complemented with the 3.x print() function performing a no-op (doing nothing) when it finds that sys.stdout is None, so that print() statements can by default safely be used - they'll simply be ignored when run with pythonw.exe
However, it follows that trying to use sys.stdout.write() and sys.stderr.write() still results in an exception.

**Comment by miigotu** [comment]
Yeah but 2.x that only should happen if you try to write to it. meh w/e as long as the fix will work. btw, the test here used to just be split in 2 parts and have a try around that.

**Comment by labrys** [comment]
im a dumbass PR'd wrong branch

**Comment by labrys** [comment]
Might need to look into this some more, unbuffered pythonw still fails so we might have additional issues.

**Comment by miigotu** [comment]
Fixed, and cherry-picked to master.
