### ISSUE TITLE
When Trakt genre on show is empty label is still shown

### ISSUE THREAD

**Issue by Rouzax** [SickRage/sickrage-issues#51]
In Jessica Jones there is no Trakt genre label but it still tries to show the little blue pill.
The pill redirects to: http://trakt.tv/shows/popular/?genres=
![image](https://cloud.githubusercontent.com/assets/4103090/11323168/0daefc90-910c-11e5-839c-f425d2bf9add.png)

**Comment by Thraxis** [comment]
I seem to have genre's listed on mine

![image](https://cloud.githubusercontent.com/assets/1131905/11326149/431a5406-9116-11e5-9b7c-313da056410b.png)

**Comment by Rouzax** [comment]
Mine also has the labels after a full refresh of the show but when there is no category there should be no label shown.

**Comment by OmgImAlexis** [comment]
Since we haven't had any other people ever report this I'm going to assume this was because of a cache issue and the only reason it showed an empty tag was because it knew one existed but didn't have the info to fill it in. I've had a look at the code and it does in fact check if a tag exists before adding anything.

**Comment by fernandog** [comment]
or nobody noticed that. All my shows have genre (did a select in db)
to fix this we need check if genre is empty before creating the "pill"
