### ISSUE TITLE
Missing button "Save settings" when disabling subtitle search

### ISSUE THREAD

**Issue by fernandog** [SickRage/sickrage-issues#64]
If I disable subtitle search, there's no button to save changes:

**Screenshot**

![image](https://cloud.githubusercontent.com/assets/2620870/11334416/ede3bea4-91bb-11e5-946f-f6954ad32941.png)

**Comment by stvkno** [comment]
Happening because `.btn .config_submitter` is within `div#content_use_subtitles` and the `.enabler` callback hides the entire div if 'Search Subtitles' is unchecked. At work so can't fix right now, but should be easy

**Comment by medariox** [comment]
@stvkno Would be great if you could fix it with a PR :+1:

**Comment by OmgImAlexis** [comment]
@fernandog is there not a save settings at the bottom like all other config pages?

**Comment by stvkno** [comment]
@OmgImAlexis I can go ahead and fix this - however just want input first. You can examine this behavior in another place; Search Settings -> NZB Search. Tick and un-tick search NZB providers to see the save changes button appear/disappear. 

I would imagine this behavior was made thinking that if the box is unchecked there are no changes to be made and thus the box is unnecessary. However, when someone decides they no longer want to search for subtitles they would uncheck the box but wouldn't have the ability to save changes because the button is hidden when the box is unchecked.

**Comment by OmgImAlexis** [comment]
Since the other config pages have a seperate save settings button under the whole div I think we should go for that. You can see what I mean if you goto `/config/general/`.
