### ISSUE TITLE
Third party apps not working Sickrage - list shows

### ISSUE THREAD

**Issue by fernandog** [SickRage/sickrage-issues#90]
They only show paused shows in the list of shows.
- ShowsRage
- DroidBeard
- NZB360

@MGaetan89 @labrys

**Comment by fernandog** [comment]
https://github.com/SickRage/sickrage-issues/issues/91

**Comment by labrys** [comment]
It looks like the paused logic is reversed as mentioned in #87

**Comment by labrys** [comment]
@MGaetan89 With paused = 1 should it return only paused or paused + unpaused

**Comment by fernandog** [comment]
Should return both

**Comment by labrys** [comment]
K got a fix, testing now and will PR.

**Comment by labrys** [comment]
@MGaetan89 The api is fixed so that when paused=1 it returns both paused and unpaused and if paused=0 it only returns shows that are not paused.  It appears that ShowsRage's show list defaults to paused=0 since paused shows do not show up.  Is there a setting I'm missing to show paused shows on the show list or should the logic be reversed here?

**Comment by labrys** [comment]
Per the description of the paused option: 'True to include paused shows, False otherwise' it's working as advertised.  What do you think about possibly changing the api though.  Make it a tri-state value.  1 returns paused 2 returns unpaused, 0/3/None returns both.

**Comment by phaseburn** [comment]
I've submitted a PR to ShowsRage that corrects this, just FYI.
